@token=32|2XrXZF6HTlyulDXtxJFVz820WjNkMouo23SXPUZy72da1978
###
POST http://aktivendb-inertia.test/auth/login 
content-type: application/json

{
    "email": "michael.uhlenberg@adfc-muenchen.de", 
    "password": "x?aktdb/#"
}
###
GET http://aktivendb-inertia.test/api/members?token={{token}}
content-type: application/json
accept: application/json
###
GET http://aktivendb-inertia.test/api/project-teams?token={{token}}
content-type: application/json
accept: application/json
###
GET http://aktivendb-inertia.test/api/member/21?token={{token}}
content-type: application/json
accept: application/json
###
GET http://aktivendb-inertia.test/api/project-team/20?token={{token}}
content-type: application/json
accept: application/json
###
