@token=30|nfBHcGRMFqrNMvbdRXlrOotJQKjj3OLTLO5cV51rae4e434e
###
POST http://aktivendb-inertia.test/auth/login 
content-type: application/json

{
    "email": "michael.uhlenberg@adfc-muenchen.de", 
    "password": "x?aktdb/#"
}
###
GET http://aktivendb-inertia.test/api/members?token={{token}}
content-type: application/json
accept: application/json
###
GET http://aktivendb-inertia.test/api/project-teams?token={{token}}
content-type: application/json
accept: application/json
###
GET http://aktivendb-inertia.test/api/member/21?token={{token}}
content-type: application/json
accept: application/json
###
PUT http://aktivendb-inertia.test/api/project-team/20?token={{token}}
content-type: application/json

{
    "email": "xxag-it_aktive@groups.adfc-muenchen.de", 
}
###
